call pathogen#runtime_append_all_bundles()
call pathogen#infect()
call pathogen#helptags()

set t_Co=256

let mapleader=","

map <Esc><Esc> :w<CR>
map <F2> :ls<CR>:b<Space>
imap ii <Esc>

nnoremap <C-n> :bnext<CR>

set nocompatible                " choose no compatibility with legacy vi
syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode
set number
set wrap linebreak nolist
set hidden

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

nnoremap <leader>, :CtrlP<cr>
nnoremap <leader>. :CtrlPTag<cr>
let g:ctrlp_working_path_mode = ''
set wildignore+=*/node_modules/*



"" From Mislav's .vimcr, https://github.com/mislav/vimfiles/blob/master/vimrc

" Auto-reload buffers when file changed on disk
set autoread

" Disable swap files; systems don't crash that often these days
set updatecount=0

" disable cursor keys in normal mode
map <Left>  :echo "no!"<cr>
map <Right> :echo "no!"<cr>
map <Up>    :echo "no!"<cr>
map <Down>  :echo "no!"<cr>
