call pathogen#runtime_append_all_bundles()
call pathogen#infect()
call pathogen#helptags()

set t_Co=256

map <Esc><Esc> :w<CR>
map <F2> :ls<CR>:b<Space>
imap ii <Esc>

nnoremap <C-n> :bnext<CR>

set nocompatible                " choose no compatibility with legacy vi
syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode
set number
set wrap linebreak nolist
set hidden

noremap <expr> <silent> <Home> col('.') == match(getline('.'),'\S')+1 ? '0' : '^'
imap <silent> <Home> <C-O><Home>

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

nnoremap <leader>, :CtrlP<cr>
nnoremap <leader>. :CtrlPTag<cr>
let g:ctrlp_working_path_mode = ''
set wildignore+=*/node_modules/*,*/app/components/*


" For local replace
nnoremap gr gd[{V%:s/<C-R>///gc<left><left><left>

" For global replace
nnoremap gR gD:%s/<C-R>///gc<left><left><left>
